#!/bin/bash

# installation script for various things
# for a fresh machine, do the steps in order: base, apps, personal-apps (optional)

if [ "$1" == "base" ]; then # set up environment

  echo "Setting up base environment..."

  cd ~/dev/dotfiles
  mkdir -p ~/.config

  # apple developer tools
  xcode-select --install

  # homebrew + homebrew cask
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  # python
  brew install python

  # node
  brew install n
  sudo n latest

  # cmake (dependency for other stuff)
  brew install cmake

  # git configs
  ln -s ~/dev/dotfiles/git/gitconfig ~/.gitconfig
  ln -s ~/dev/dotfiles/git/gitignore ~/.gitignore

  # fish
  brew install fish
  echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/fish
  ln -s ~/dev/dotfiles/fish/config.fish ~/.config/fish/config.fish
  ln -s ~/dev/dotfiles/fish/fishfile ~/.config/fish/fishfile

  # fisher
  curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
  fisher

  #tmux
  brew install tmux
  git clone git@github.com:/tmux-plugins/tpm ~/.tmux/plugins/tpm

  # nvim
  brew install nvim
  pip3 install --upgrade neovim
  mkdir -p ~/.config/nvim
  ln -s ~/dev/dotfiles/vim/vimrc ~/.config/nvim/init.vim
  ln -s ~/dev/dotfiles/vim/vimrc ~/.vimrc

  # fzf and ripgrep
  brew install fzf
  brew install ripgrep

  # gist
  brew install gist

  # ctags
  brew install ctags

  # tern
  ln -s ~/dev/dotfiles/tern/tern-project ~/.tern-project

elif [ "$1" == "apps" ]; then # install apps

  echo "Installing apps..."

  brew cask install alfred
  brew cask install iterm2
  brew cask install bettertouchtool
  brew cask install istat-menus
  brew cask install dropshare
  brew cask install slack
  brew cask install yakyak
  brew cask install sip
  brew cask install daisydisk
  brew cask install sketch
  brew cask install virtualbox
  brew cask install adobe-creative-cloud

  # mac app store cli
  brew install mas

  mas install 419330170 # moom
  mas install 1263070803 # lungo
  mas install 975937182 # fantastical 2
  mas install 1017470484 # next meeting
  mas install 512617038 # snappy
  mas install 904280696 # things 3
  mas install 668208984 # giphy capture
  mas install 1091189122 # bear
  mas install 1320666476 # wipr

elif [ "$1" == "personal-apps" ]; then # install apps for personal use

  echo "Installing personal apps..."

  brew cask install transmission
  brew cask install private-internet-access
  brew cask install beamer

else

  echo "Available options: base, apps, personal-apps"

fi
