set regexpengine=1
set runtimepath^=~/dotfiles/vim
set packpath^=~/dotfiles/vim

set clipboard=unnamed

set t_Co=256
set background=dark

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
filetype on
filetype plugin on
filetype indent on
syntax on
colorscheme tender
set smartindent
set autoindent
set nowrap
set hlsearch
set number
highlight LineNr ctermfg=darkgrey
" set showmatch

set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline_theme='tender'

" delete all trailing space
autocmd BufWritePre * :%s/\s\+$//e

set mouse=a " enables the mouse
set history=1000 " more undo'ing
set incsearch " incrementally search/highlight as you're typing
set scrolloff=5 " start scrolling when the cursor is five lines away from the edge of screen
set cursorline " highlight the entire line that your cursor is on
" hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
" hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white

let g:jsx_ext_required = 0
let g:netrw_banner=0

" better split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" better split opening
set splitbelow
set splitright

" show invisibles
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<
set list

let g:indent_guides_enable_on_vim_startup = 1

function! AirlineInit()
  let g:airline_section_y = airline#section#create(['filetype'])
  let g:airline_section_x = ""
endfunction

autocmd User AirlineAfterInit call AirlineInit()

let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

set backspace=indent,eol,start

set guioptions=
set guifont=Meslo\ LG\ S\ Regular\ for\ Powerline:h10
set termguicolors

let g:indent_guides_auto_colors = 0
hi IndentGuidesOdd guibg=#242424
hi IndentGuidesEven guibg=#2c2c2c
